targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "^lib/{{dir}}/{{file_name}}.dart": "lib/{{dir}}/generated/{{file_name}}.g.dart"
