name: more_sleep
description: "I want to sleep more."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.2.1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.5
  flutter_riverpod: ^2.3.6
  go_router: ^13.1.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: '>=4.0.0 <5.0.0'
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.5
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.7

flutter:
  uses-material-design: true


  fonts:
      - family: Pretendard
        fonts:
          - asset: fonts/Pretendard-Regular.ttf
            weight: 400
          - asset: fonts/Pretendard-Medium.ttf
            weight: 500
          - asset: fonts/Pretendard-SemiBold.ttf
            weight: 600
          - asset: fonts/Pretendard-Bold.ttf
            weight: 700
