name: more_sleep
description: "I want to sleep more."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.2.1
  flutter:
    sdk: flutter
  workmanager: ^0.5.2
  flutter_local_notifications: ^9.1.5
  flutter_riverpod: ^2.3.6
  go_router: ^13.1.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.7

flutter:
  uses-material-design: true


  fonts:
      - family: Pretendard
        fonts:
          - asset: fonts/Pretendard-Regular.ttf
            weight: 400
          - asset: fonts/Pretendard-Medium.ttf
            weight: 500
          - asset: fonts/Pretendard-SemiBold.ttf
            weight: 600
          - asset: fonts/Pretendard-Bold.ttf
            weight: 700
